### PR TITLE
Issue #219 fix thrown exception

### LINKED ISSUE #219: Exception is thrown when user edits game time in playoff
Create playoff > Add some teams > Set game time for any game

- [x] #238 - Reproduce all scenarious when exception is appeared
- [x] #239 - Fix exception
- [x] #263 - Add UTs to test the corresponding logic change
- [ ] #240 - Test changes and results

### PR DESCRIPTION
**Pull request by NataliiaBidiuk**
### Summary
Add one condition when we check that gameFinished.HomeTeam.Id can be null, because without this in code HomeTeam.Id = 0, it provides an exception with a foreign key. 

closes #219 

### Areas Of Interest
It doesn`t work when we have duplicate games, but it is related to Sofia issue, and when it will be in master with Sofia code it should be good.

#### Design

- [ ] Web API layer contains as little logic as possible
- [ ] Domain objects use semantic names

#### Perfromance

- [ ] In case of any DB query was changed: attach generated SQL for review
- [ ] Number of DB roundtrips should be as low as possible

#### Unit Tests

- [ ] Naming: Initial state and expected result are properly stated
- [ ] Test follows [AAA](https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80) pattern.
- [ ] Test is Isolated
- [ ] Mock instances and expected instances do not share references
- [ ] When new property is added all related comparers are updated

### CODE REVIEW

**Comment by sdiachen** [comment]
Look carefully through checklist. Did you miss something?

**Comment by oleggerus** [comment]
to write UT?

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs [hunk 1]
```diff
@@ -1648,6 +1648,42 @@ public void Edit_GameValid_GameEdited()
             VerifyEditGame(game, Times.Once());
         }
 
+        /// <summary>
+        /// Test for Edit method. Game object in PlayOff contains valid data. 
+        /// No exceprtion returns and game is edited successfully
+        /// </summary>
+        [TestMethod]
+        public void Edit_GameTimeForPlayOffChanged_NoException()
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Your case is to wide. We need to make it more specific.

You've added condition stating HomeTeamId!=null. What does it mean from user perspective?

Comment (oleggerus) [reply tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: @sdiachen It means that if home team in the game isn't known, we can't find out the winner of this game. And we can't pass the winner of this game to the next round too.

Comment (oleggerus) [reply tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Is it possible that I don't need to check if game time changes but only if the winner of the game is chosen correctly?

Comment (sdiachen) [reply tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Your case here is that you don't have all teams defined.

_EditTimeForPlannedGame_GameSaved
_EditTimeForUpcomingGameSlot_GameSaved

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs [hunk 2]
```diff
@@ -1648,6 +1648,80 @@ public void Edit_GameValid_GameEdited()
...
+
+            var testGameForEdit = games[5];
+            testGameForEdit.GameDate = new DateTime(2016, 4, 3, 0, 0, 0);
+
+            MockAllTournamentQueries(testTournament);
+            MockGetTournamentResults(TOURNAMENT_ID, games);
+
+            //Act
+            var sut = BuildSUT();
+            try
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Why do you need try catch?

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs [hunk 3]
```diff
@@ -1648,6 +1648,80 @@ public void Edit_GameValid_GameEdited()
...
+        {
+            //Arrange
+            bool isExceprionThrown = false;
+            var testTournament = CreatePlayoffTournament();
+            var games = new GameTestFixture()
+                .TestEmptyGamePlayoffSchedule()
+                .Build();
+
+            var testGameForEdit = games[5];
+            testGameForEdit.GameDate = new DateTime(2016, 4, 3, 0, 0, 0);
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Does  this date mean anything?

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs [hunk 4]
```diff
@@ -1648,6 +1648,80 @@ public void Edit_GameValid_GameEdited()
...
+        public void Edit_ChangeTimeForPlayOffGameWithUnknownTeams_GameSaved()
+        {
+            //Arrange
+            bool isExceprionThrown = false;
+            var testTournament = CreatePlayoffTournament();
+            var games = new GameTestFixture()
+                .TestEmptyGamePlayoffSchedule()
+                .Build();
+
+            var testGameForEdit = games[5];
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Why 5?

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs [hunk 5]
```diff
@@ -1648,6 +1648,80 @@ public void Edit_GameValid_GameEdited()
...
+
+        /// <summary>
+        /// Test for Edit method. Change time for game in second round with known teams. 
+        /// No exceprtion returns and game is edited successfully.
+        /// </summary>
+        [TestMethod]
+        public void Edit_ChangeTimeForPlayOffGameWithKnownTeams_GameSaved()
+        {
+            //Arrange
+            bool isExceprionThrown = false;
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Spelling

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs (hunk 4 above)
Comment (oleggerus) [reply tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Because teams in the first round are already known and it worked good in all cases.
So we choose game in second round with unknown teams.

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs (hunk 3 above)
Comment (oleggerus) [reply tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Created tournament has start and end date. That's why I chose game time in this special range.

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs (hunk 5 above)
Comment (oleggerus) [reply tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: @sdiachen  can you give advice?

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs [hunk 6]
```diff
@@ -1648,6 +1648,62 @@ public void Edit_GameValid_GameEdited()
...
+        [TestMethod]
+        public void Edit_ChangeTimeForPlayOffGameWithUnknownTeams_GameSaved()
+        {
+            //Arrange
+            var testTournament = CreatePlayoffTournament();
+            var games = new GameTestFixture()
+                .TestEmptyGamePlayoffSchedule()
+                .Build();
+
+            var testGameForEdit = games.FirstOrDefault(g => g.Round == 2);
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Wrap this code into methods with descriptive names

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs [hunk 7]
```diff
@@ -1648,6 +1648,62 @@ public void Edit_GameValid_GameEdited()
...
+        public void Edit_ChangeTimeForPlayOffGameWithDefinedTeams_GameSaved()
+        {
+            //Arrange
+            var testTournament = CreatePlayoffTournament();
+            var games = new GameTestFixture()
+                .TestEmptyGamePlayoffSchedule()
+                .Build();
+
+            var testGameForEdit = GetTestGameFromSecondRoundinPlayOff(games);
+            testGameForEdit.HomeTeamId = 1;
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Should I point everywhere?

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs [hunk 8]
```diff
@@ -1648,6 +1648,58 @@ public void Edit_GameValid_GameEdited()
...
+            //Assert
+            VerifyEditGame(testGameForEdit, Times.Once());
+        }
+
+        /// <summary>
+        /// Test for Edit method. Change time for planned game in second round with defined teams. 
+        /// No exceprtion returns and game is edited successfully.
+        /// </summary>
+        [TestMethod]
+        public void Edit_ChangeTimeForPlayOffGameWithDefinedTeams_GameSaved()
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: So what is the difference in those two tests? Both methods are identical

Comment (oleggerus) [reply tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Inattention. Repaired it.

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs [hunk 9]
```diff
@@ -2456,6 +2505,20 @@ private static Game CreateGameToEdit(int anotherPlayoffGameId)
                 .WithDayOff()
                 .Build();
         }
+        private static Game GetTestGameForEditFromSecondRoundInPlayOff(IEnumerable<Game> games)
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: You say GetTestGame but assign date?

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs [hunk 10]
```diff
@@ -2456,6 +2505,20 @@ private static Game CreateGameToEdit(int anotherPlayoffGameId)
...
+        {
+            var testTeam = games.FirstOrDefault(g => g.Round == 2);
+            testTeam.GameDate = DateTime.Parse(TOURNAMENT_DATE_START);
+
+            return testTeam;
+        }
+
+        private static void DefineTeamsInGame(Game game)
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: Think about better name. Think about use case user might see

File: tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs (hunk 9 above)
Comment (oleggerus) [reply tests/VolleyManagement.UnitTests/Services/GameService/GameServiceTests.cs]: done
