### PR TITLE
Fixed IsTechnical defeat mapping

### LINKED ISSUE #41: Technical Defeat is not saved
1. Create/Edit game result
2. Set Technical defeat flag
3. Save

### PR DESCRIPTION
**Pull request by sdiachen**
closes #41

### CODE REVIEW

File: VolleyManagement.UnitTests/Mvc/Controllers/GameResultsControllerTests.cs [hunk 1]
```diff
@@ -395,9 +398,41 @@ private GameResultsController BuildSUT()
...
-        private void VerifyEditGameResult(Times times)
+        private static GameResultViewModel CreateResultViewModel()
         {
-            _gameServiceMock.Verify(ts => ts.EditGameResult(It.IsAny<Game>()), times);
+            var result = new GameResultViewModelBuilder()
+                            .WithTechnicalDefeat(true)
+                            .WithPenalty(new Penalty
+                            {
+                                Amount = 1,
+                                Description = "asd",
```
Comment (dmshapoval) [inline VolleyManagement.UnitTests/Mvc/Controllers/GameResultsControllerTests.cs]: Description to constant?

Comment (sdiachen) [reply VolleyManagement.UnitTests/Mvc/Controllers/GameResultsControllerTests.cs]: Not sure about that. It won't give too much of a value in scope of the test.
