### PR TITLE
Issue #351 fix tests for modified ITeamService methods

### LINKED ISSUE #351: Fix tests for modified methods in TeamService.
Parent #298 

After adding 3 new methods for ITeamService, some of existing ones were modified.
Fix corresponding UTs.

### PR DESCRIPTION
**Pull request by Myroslavv**
### Summary

Fix tests in TeamServiceTests (all but Add/RemovePlayers, ChangeCaptain).

closes #351 

### Areas Of Interest

_Any specific places you want to bring attention of the reviewers? Some places you are uncertain in/some design decisions. (If none remove this section)_

#### Design

- [ ] Web API layer contains as little logic as possible
- [ ] Domain objects use semantic names

#### Perfromance

- [ ] In case of any DB query was changed: attach generated SQL for review
- [ ] Number of DB roundtrips should be as low as possible

#### Unit Tests

- [ ] Naming: Initial state and expected result are properly stated
- [ ] Test follows [AAA](https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80) pattern.
- [ ] Test is Isolated
- [ ] Mock instances and expected instances do not share references
- [ ] When new property is added all related comparers are updated

### CODE REVIEW

File: tests/VolleyManagement.UnitTests/Services/TeamService/TeamServiceTests.cs [hunk 1]
```diff
@@ -160,25 +162,22 @@ public void GetTeamCaptain_CaptainExist_PlayerReturned()
         /// Test for Create() method. The method should create a new team.
         /// </summary>
         [TestMethod]
-        public void Create_TeamPassed_TeamCreated()
+        public void Create_CreateTeamDtoPassed_DtoAddedByRepository()
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/TeamService/TeamServiceTests.cs]: Why did you rename last part?

Comment (Myroslavv) [reply tests/VolleyManagement.UnitTests/Services/TeamService/TeamServiceTests.cs]: To follow the 'Assert' part of test.
Is it better to revert change of the name, along with adding some logic so it would follow the description?

Comment (sdiachen) [reply tests/VolleyManagement.UnitTests/Services/TeamService/TeamServiceTests.cs]: In Assert part of the test you have "VerifyCreateTeam". I do not follow you probably.
