### PR TITLE
Issue_#208 Fix thorowing error in schedule

### LINKED ISSUE #208: Schedule view throws error in Playoff
1. Create playoff tournament
2. Add 6 teams using Apply for tournament workflow
3. Approve all teams
4. Go to Schedule

Subtasks:
- [x] #224 Fix internal server error
- [x] #225 Change tests
- [ ] #226  Manual QA

**AR:** Internal server error

### PR DESCRIPTION
**Pull request by ViznyakS**
### Summary

1) Use tournamentService insted of tournamentRepository to correct add teams to tournament.
2) Change corresponded tests

Closes #208 

### Areas Of Interest

image
And test:
image

#### Design

- [ ] Web API layer contains as little logic as possible
- [ ] Domain objects use semantic names

#### Perfromance

- [ ] In case of any DB query was changed: attach generated SQL for review
- [ ] Number of DB roundtrips should be as low as possible

#### Unit Tests

- [ ] Naming: Initial state and expected result are properly stated
- [ ] Test follows [AAA](https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80) pattern.
- [ ] Test is Isolated
- [ ] Mock instances and expected instances do not share references
- [ ] When new property is added all related comparers are updated

### CODE REVIEW

**Comment by sdiachen** [comment]
No reviews until sprint is planned properly.

**Comment by sdiachen** [comment]
Why checks haven't passed?

File: tests/VolleyManagement.UnitTests/Services/TournamentRequestService/TournamentRequestServiceTests.cs [hunk 1]
```diff
@@ -330,10 +329,9 @@ private void MockGetAllTournamentRequestQuery(TournamentRequest testData)
             _getRequestByAllQueryMock.Setup(tr => tr.Execute(It.IsAny<FindByTeamTournamentCriteria>())).Returns(testData);
         }
 
-        private void VerifyAddedTeam(int requestId, int tournamentId, int groupId, Times times, Times unitOfWorkTimes)
+        private void VerifyAddedTeam(Times times)
```
Comment (sdiachen) [inline tests/VolleyManagement.UnitTests/Services/TournamentRequestService/TournamentRequestServiceTests.cs]: Method name does not correspond to its meaning. Current name suggests team is added to db.
